- name: Remote Jupyter Book Publish
  # You may pin to the exact commit or the version.
  # uses: dzsquared/jupyter-publish-action@17fafad07a497121e014093629aa3a62a020cffa
  uses: dzsquared/jupyter-publish-action@v0.1.0
  with:
    # Jupyter Book to Release (defaults to whole repository)
    directory: # default is .
    # Release name
    releasename: 
    # Book name
    bookname: 
    # Version number
    versionnumber: 
    # Language id
    languageid: # default is EN
    # GitHub token for action context
    githubtoken: 
